ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}

ARG PUBKEY
ARG PRIVKEY
ARG EMAIL
ARG PASSPHRASE
ENV PUBKEY=$PUBKEY
ENV PRIVKEY=$PRIVKEY
ENV EMAIL=$EMAIL
ENV PASSPHRASE=$PASSPHRASE

COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "sh", "-c", "/entrypoint.sh" ]
