# This is a basic workflow to help you get started with Actions

name: turnip-ppa-update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ppa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This will create one job for each Ubuntu version supported by official Docker image 
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [20.04, 22.04, 24.04, 24.10, 25.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install podman
        run: |
          cd "$GITHUB_WORKSPACE"
          sudo apt update
          sudo apt install -y podman
      
      # Runs a set of commands using the runners shell
      - name: Run build script inside podman container for ${{ matrix.ubuntu_version }}
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PUBKEY: ${{ secrets.PUBKEY }}
          PRIVKEY: ${{ secrets.PRIVKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          UBUNTU_VERSION: ${{ matrix.ubuntu_version }}
        run: |
          cd "$GITHUB_WORKSPACE"
          podman build -f Dockerfile -t turnip-build --build-arg EMAIL="$EMAIL" --build-arg PRIVKEY="$PRIVKEY" --build-arg PUBKEY="$PUBKEY" --build-arg PASSPHRASE="$PASSPHRASE" --build-arg UBUNTU_VERSION="$UBUNTU_VERSION"
          podman run --security-opt seccomp=unconfined turnip-build

      # - name: Run build script inside podman container for 24.10
      #   env:
      #     EMAIL: ${{ secrets.EMAIL }}
      #     PUBKEY: ${{ secrets.PUBKEY }}
      #     PRIVKEY: ${{ secrets.PRIVKEY }}
      #     PASSPHRASE: ${{ secrets.PASSPHRASE }}
      #   run: |
      #     cd "$GITHUB_WORKSPACE"
      #     podman build -f Dockerfile -t turnip-build --build-arg EMAIL="$EMAIL" --build-arg PRIVKEY="$PRIVKEY" --build-arg PUBKEY="$PUBKEY" --build-arg PASSPHRASE="$PASSPHRASE" --build-arg UBUNTU_VERSION="24.10"
      #     podman run --security-opt seccomp=unconfined turnip-build

